# Generated by Django 4.2.3 on 2023-07-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to="article/"),
        ),
    ]
